name: Publish crate

on:
  push:
    tags: [v*]

permissions:
  contents: write

jobs:
  build-for-apple:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cross
        run: cargo install cross

      - name: Add target to rustup
        run: rustup target add x86_64-apple-darwin

      - name: Build for Apple x86_64
        run: cross build --target x86_64-apple-darwin --release
        env:
          CARGO_TARGET_DIR: target/x86_64-apple-darwin

      - name: Build for Apple aarch64
        run: cross build --target aarch64-apple-darwin --release
        env:
          CARGO_TARGET_DIR: target/aarch64-apple-darwin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: |
            target/x86_64-apple-darwin/clipcat
            target/aarch64-apple-darwin/clipcat

  build-and-release:
    runs-on: ubuntu-latest
    needs: build-for-apple

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cross
        run: cargo install cross

      - name: Build for Linux amd64
        run: cross build --target x86_64-unknown-linux-gnu --release
        env:
          CARGO_TARGET_DIR: target/x86_64-unknown-linux-gnu

      - name: Build for Linux arm
        run: cross build --target arm-unknown-linux-gnueabihf --release
        env:
          CARGO_TARGET_DIR: target/arm-unknown-linux-gnueabihf

      - name: Build for Windows
        run: cross build --target x86_64-pc-windows-gnu --release
        env:
          CARGO_TARGET_DIR: target/x86_64-pc-windows-gnu

      - name: Download Apple x86_64 artifact
        uses: actions/download-artifact@v2
        with:
          name: x86_64-apple-darwin
          path: target/x86_64-apple-darwin

      - name: Download Apple aarch64 artifact
        uses: actions/download-artifact@v2
        with:
          name: aarch64-apple-darwin
          path: target/aarch64-apple-darwin

      - name: Release ${{ github.ref_name }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/x86_64-unknown-linux-gnu/clipcat
            target/arm-unknown-linux-gnueabihf/clipcat
            target/x86_64-pc-windows-gnu/clipcat.exe
            target/x86_64-apple-darwin/release/clipcat
            target/aarch64-apple-darwin/release/clipcat
